spring:
    application:
        name: mascotas-perdidas-service
    datasource:
      url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      username: ${USER}
      password: ${PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 600000
        connection-timeout: 30000
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          jdbc:
            time_zone: UTC
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  name: "dtlfboijw"
  key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}