spring:
    application:
        name: mascotas-perdidas-service
    datasource:
      url: jdbc:postgresql://${DATABASE_URL}?sslmode=require
      username: ${USER}
      password: ${PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 600000
        connection-timeout: 30000
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL}
      password: ${EMAIL_PASSWORD}
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
          debug: true
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          jdbc:
            time_zone: UTC
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  name: "dtlfboijw"
  key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: mascotas-perdidas
    ttl-seconds: 2592000
  token:
    pepper: ${TOKEN_PEPPER}

server:
  port: ${PORT:10000}
